server:
  id: 1
  port: 7091
  websocket:
    port: 8987
logging:
  config: classpath:log4j2.yml
#
spring:
  application:
    name: nett_server
  dubbo:
    protocol:
      name: dubbo
      port: 20801
    consumer:
      check: false
      timeout: 5000
      retries: 0
    registry:
      address: zookeeper://127.0.0.1:2181
  profiles:
    active: dev
#  redis:
#    database: 1
#    host: 127.0.0.1
#    port: 6379
#    password:
