// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extraction.proto

package com.zihai.proto.entity;

public final class People {
  private People() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code peple.methodCode}
   */
  public enum methodCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>saveVisitor = 0;</code>
     */
    saveVisitor(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>saveVisitor = 0;</code>
     */
    public static final int saveVisitor_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static methodCode valueOf(int value) {
      return forNumber(value);
    }

    public static methodCode forNumber(int value) {
      switch (value) {
        case 0: return saveVisitor;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<methodCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        methodCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<methodCode>() {
            public methodCode findValueByNumber(int number) {
              return methodCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zihai.proto.entity.People.getDescriptor().getEnumTypes().get(0);
    }

    private static final methodCode[] VALUES = values();

    public static methodCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private methodCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:peple.methodCode)
  }

  public interface SonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:peple.Son)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *年龄
     * </pre>
     *
     * <code>int32 age = 2;</code>
     */
    int getAge();
  }
  /**
   * Protobuf type {@code peple.Son}
   */
  public  static final class Son extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:peple.Son)
      SonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Son.newBuilder() to construct.
    private Son(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Son() {
      name_ = "";
      age_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Son(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zihai.proto.entity.People.internal_static_peple_Son_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zihai.proto.entity.People.internal_static_peple_Son_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zihai.proto.entity.People.Son.class, com.zihai.proto.entity.People.Son.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <pre>
     *年龄
     * </pre>
     *
     * <code>int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zihai.proto.entity.People.Son)) {
        return super.equals(obj);
      }
      com.zihai.proto.entity.People.Son other = (com.zihai.proto.entity.People.Son) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zihai.proto.entity.People.Son parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zihai.proto.entity.People.Son parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zihai.proto.entity.People.Son parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zihai.proto.entity.People.Son parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zihai.proto.entity.People.Son parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zihai.proto.entity.People.Son parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zihai.proto.entity.People.Son parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zihai.proto.entity.People.Son parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zihai.proto.entity.People.Son parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zihai.proto.entity.People.Son parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zihai.proto.entity.People.Son parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zihai.proto.entity.People.Son parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zihai.proto.entity.People.Son prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code peple.Son}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:peple.Son)
        com.zihai.proto.entity.People.SonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zihai.proto.entity.People.internal_static_peple_Son_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zihai.proto.entity.People.internal_static_peple_Son_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zihai.proto.entity.People.Son.class, com.zihai.proto.entity.People.Son.Builder.class);
      }

      // Construct using com.zihai.proto.entity.People.Son.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zihai.proto.entity.People.internal_static_peple_Son_descriptor;
      }

      public com.zihai.proto.entity.People.Son getDefaultInstanceForType() {
        return com.zihai.proto.entity.People.Son.getDefaultInstance();
      }

      public com.zihai.proto.entity.People.Son build() {
        com.zihai.proto.entity.People.Son result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zihai.proto.entity.People.Son buildPartial() {
        com.zihai.proto.entity.People.Son result = new com.zihai.proto.entity.People.Son(this);
        result.name_ = name_;
        result.age_ = age_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zihai.proto.entity.People.Son) {
          return mergeFrom((com.zihai.proto.entity.People.Son)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zihai.proto.entity.People.Son other) {
        if (other == com.zihai.proto.entity.People.Son.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zihai.proto.entity.People.Son parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zihai.proto.entity.People.Son) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       *年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       *年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:peple.Son)
    }

    // @@protoc_insertion_point(class_scope:peple.Son)
    private static final com.zihai.proto.entity.People.Son DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zihai.proto.entity.People.Son();
    }

    public static com.zihai.proto.entity.People.Son getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Son>
        PARSER = new com.google.protobuf.AbstractParser<Son>() {
      public Son parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Son(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Son> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Son> getParserForType() {
      return PARSER;
    }

    public com.zihai.proto.entity.People.Son getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ParentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:peple.Parent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *年龄
     * </pre>
     *
     * <code>int32 age = 2;</code>
     */
    int getAge();

    /**
     * <pre>
     *喜好
     * </pre>
     *
     * <code>string like = 3;</code>
     */
    java.lang.String getLike();
    /**
     * <pre>
     *喜好
     * </pre>
     *
     * <code>string like = 3;</code>
     */
    com.google.protobuf.ByteString
        getLikeBytes();

    /**
     * <pre>
     *文件
     * </pre>
     *
     * <code>.peple.Son son = 4;</code>
     */
    boolean hasSon();
    /**
     * <pre>
     *文件
     * </pre>
     *
     * <code>.peple.Son son = 4;</code>
     */
    com.zihai.proto.entity.People.Son getSon();
    /**
     * <pre>
     *文件
     * </pre>
     *
     * <code>.peple.Son son = 4;</code>
     */
    com.zihai.proto.entity.People.SonOrBuilder getSonOrBuilder();
  }
  /**
   * Protobuf type {@code peple.Parent}
   */
  public  static final class Parent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:peple.Parent)
      ParentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Parent.newBuilder() to construct.
    private Parent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Parent() {
      name_ = "";
      age_ = 0;
      like_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Parent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              like_ = s;
              break;
            }
            case 34: {
              com.zihai.proto.entity.People.Son.Builder subBuilder = null;
              if (son_ != null) {
                subBuilder = son_.toBuilder();
              }
              son_ = input.readMessage(com.zihai.proto.entity.People.Son.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(son_);
                son_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zihai.proto.entity.People.internal_static_peple_Parent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zihai.proto.entity.People.internal_static_peple_Parent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zihai.proto.entity.People.Parent.class, com.zihai.proto.entity.People.Parent.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <pre>
     *年龄
     * </pre>
     *
     * <code>int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int LIKE_FIELD_NUMBER = 3;
    private volatile java.lang.Object like_;
    /**
     * <pre>
     *喜好
     * </pre>
     *
     * <code>string like = 3;</code>
     */
    public java.lang.String getLike() {
      java.lang.Object ref = like_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        like_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *喜好
     * </pre>
     *
     * <code>string like = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLikeBytes() {
      java.lang.Object ref = like_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        like_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SON_FIELD_NUMBER = 4;
    private com.zihai.proto.entity.People.Son son_;
    /**
     * <pre>
     *文件
     * </pre>
     *
     * <code>.peple.Son son = 4;</code>
     */
    public boolean hasSon() {
      return son_ != null;
    }
    /**
     * <pre>
     *文件
     * </pre>
     *
     * <code>.peple.Son son = 4;</code>
     */
    public com.zihai.proto.entity.People.Son getSon() {
      return son_ == null ? com.zihai.proto.entity.People.Son.getDefaultInstance() : son_;
    }
    /**
     * <pre>
     *文件
     * </pre>
     *
     * <code>.peple.Son son = 4;</code>
     */
    public com.zihai.proto.entity.People.SonOrBuilder getSonOrBuilder() {
      return getSon();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (!getLikeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, like_);
      }
      if (son_ != null) {
        output.writeMessage(4, getSon());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (!getLikeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, like_);
      }
      if (son_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSon());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zihai.proto.entity.People.Parent)) {
        return super.equals(obj);
      }
      com.zihai.proto.entity.People.Parent other = (com.zihai.proto.entity.People.Parent) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && getLike()
          .equals(other.getLike());
      result = result && (hasSon() == other.hasSon());
      if (hasSon()) {
        result = result && getSon()
            .equals(other.getSon());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + LIKE_FIELD_NUMBER;
      hash = (53 * hash) + getLike().hashCode();
      if (hasSon()) {
        hash = (37 * hash) + SON_FIELD_NUMBER;
        hash = (53 * hash) + getSon().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zihai.proto.entity.People.Parent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zihai.proto.entity.People.Parent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zihai.proto.entity.People.Parent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zihai.proto.entity.People.Parent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zihai.proto.entity.People.Parent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zihai.proto.entity.People.Parent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zihai.proto.entity.People.Parent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zihai.proto.entity.People.Parent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zihai.proto.entity.People.Parent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zihai.proto.entity.People.Parent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zihai.proto.entity.People.Parent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zihai.proto.entity.People.Parent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zihai.proto.entity.People.Parent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code peple.Parent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:peple.Parent)
        com.zihai.proto.entity.People.ParentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zihai.proto.entity.People.internal_static_peple_Parent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zihai.proto.entity.People.internal_static_peple_Parent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zihai.proto.entity.People.Parent.class, com.zihai.proto.entity.People.Parent.Builder.class);
      }

      // Construct using com.zihai.proto.entity.People.Parent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        like_ = "";

        if (sonBuilder_ == null) {
          son_ = null;
        } else {
          son_ = null;
          sonBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zihai.proto.entity.People.internal_static_peple_Parent_descriptor;
      }

      public com.zihai.proto.entity.People.Parent getDefaultInstanceForType() {
        return com.zihai.proto.entity.People.Parent.getDefaultInstance();
      }

      public com.zihai.proto.entity.People.Parent build() {
        com.zihai.proto.entity.People.Parent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zihai.proto.entity.People.Parent buildPartial() {
        com.zihai.proto.entity.People.Parent result = new com.zihai.proto.entity.People.Parent(this);
        result.name_ = name_;
        result.age_ = age_;
        result.like_ = like_;
        if (sonBuilder_ == null) {
          result.son_ = son_;
        } else {
          result.son_ = sonBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zihai.proto.entity.People.Parent) {
          return mergeFrom((com.zihai.proto.entity.People.Parent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zihai.proto.entity.People.Parent other) {
        if (other == com.zihai.proto.entity.People.Parent.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getLike().isEmpty()) {
          like_ = other.like_;
          onChanged();
        }
        if (other.hasSon()) {
          mergeSon(other.getSon());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zihai.proto.entity.People.Parent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zihai.proto.entity.People.Parent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       *年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       *年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object like_ = "";
      /**
       * <pre>
       *喜好
       * </pre>
       *
       * <code>string like = 3;</code>
       */
      public java.lang.String getLike() {
        java.lang.Object ref = like_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          like_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *喜好
       * </pre>
       *
       * <code>string like = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLikeBytes() {
        java.lang.Object ref = like_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          like_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *喜好
       * </pre>
       *
       * <code>string like = 3;</code>
       */
      public Builder setLike(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        like_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *喜好
       * </pre>
       *
       * <code>string like = 3;</code>
       */
      public Builder clearLike() {
        
        like_ = getDefaultInstance().getLike();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *喜好
       * </pre>
       *
       * <code>string like = 3;</code>
       */
      public Builder setLikeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        like_ = value;
        onChanged();
        return this;
      }

      private com.zihai.proto.entity.People.Son son_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zihai.proto.entity.People.Son, com.zihai.proto.entity.People.Son.Builder, com.zihai.proto.entity.People.SonOrBuilder> sonBuilder_;
      /**
       * <pre>
       *文件
       * </pre>
       *
       * <code>.peple.Son son = 4;</code>
       */
      public boolean hasSon() {
        return sonBuilder_ != null || son_ != null;
      }
      /**
       * <pre>
       *文件
       * </pre>
       *
       * <code>.peple.Son son = 4;</code>
       */
      public com.zihai.proto.entity.People.Son getSon() {
        if (sonBuilder_ == null) {
          return son_ == null ? com.zihai.proto.entity.People.Son.getDefaultInstance() : son_;
        } else {
          return sonBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *文件
       * </pre>
       *
       * <code>.peple.Son son = 4;</code>
       */
      public Builder setSon(com.zihai.proto.entity.People.Son value) {
        if (sonBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          son_ = value;
          onChanged();
        } else {
          sonBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *文件
       * </pre>
       *
       * <code>.peple.Son son = 4;</code>
       */
      public Builder setSon(
          com.zihai.proto.entity.People.Son.Builder builderForValue) {
        if (sonBuilder_ == null) {
          son_ = builderForValue.build();
          onChanged();
        } else {
          sonBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *文件
       * </pre>
       *
       * <code>.peple.Son son = 4;</code>
       */
      public Builder mergeSon(com.zihai.proto.entity.People.Son value) {
        if (sonBuilder_ == null) {
          if (son_ != null) {
            son_ =
              com.zihai.proto.entity.People.Son.newBuilder(son_).mergeFrom(value).buildPartial();
          } else {
            son_ = value;
          }
          onChanged();
        } else {
          sonBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *文件
       * </pre>
       *
       * <code>.peple.Son son = 4;</code>
       */
      public Builder clearSon() {
        if (sonBuilder_ == null) {
          son_ = null;
          onChanged();
        } else {
          son_ = null;
          sonBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *文件
       * </pre>
       *
       * <code>.peple.Son son = 4;</code>
       */
      public com.zihai.proto.entity.People.Son.Builder getSonBuilder() {
        
        onChanged();
        return getSonFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *文件
       * </pre>
       *
       * <code>.peple.Son son = 4;</code>
       */
      public com.zihai.proto.entity.People.SonOrBuilder getSonOrBuilder() {
        if (sonBuilder_ != null) {
          return sonBuilder_.getMessageOrBuilder();
        } else {
          return son_ == null ?
              com.zihai.proto.entity.People.Son.getDefaultInstance() : son_;
        }
      }
      /**
       * <pre>
       *文件
       * </pre>
       *
       * <code>.peple.Son son = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zihai.proto.entity.People.Son, com.zihai.proto.entity.People.Son.Builder, com.zihai.proto.entity.People.SonOrBuilder> 
          getSonFieldBuilder() {
        if (sonBuilder_ == null) {
          sonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zihai.proto.entity.People.Son, com.zihai.proto.entity.People.Son.Builder, com.zihai.proto.entity.People.SonOrBuilder>(
                  getSon(),
                  getParentForChildren(),
                  isClean());
          son_ = null;
        }
        return sonBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:peple.Parent)
    }

    // @@protoc_insertion_point(class_scope:peple.Parent)
    private static final com.zihai.proto.entity.People.Parent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zihai.proto.entity.People.Parent();
    }

    public static com.zihai.proto.entity.People.Parent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Parent>
        PARSER = new com.google.protobuf.AbstractParser<Parent>() {
      public Parent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Parent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Parent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Parent> getParserForType() {
      return PARSER;
    }

    public com.zihai.proto.entity.People.Parent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peple_Son_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peple_Son_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peple_Parent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peple_Parent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020extraction.proto\022\005peple\" \n\003Son\022\014\n\004name" +
      "\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\"J\n\006Parent\022\014\n\004name\030\001 " +
      "\001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004like\030\003 \001(\t\022\027\n\003son\030\004 " +
      "\001(\0132\n.peple.Son*\035\n\nmethodCode\022\017\n\013saveVis" +
      "itor\020\00025\n\014HelloService\022%\n\010sayHello\022\r.pep" +
      "le.Parent\032\n.peple.SonB \n\026com.zihai.proto" +
      ".entityB\006Peopleb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_peple_Son_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_peple_Son_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peple_Son_descriptor,
        new java.lang.String[] { "Name", "Age", });
    internal_static_peple_Parent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_peple_Parent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peple_Parent_descriptor,
        new java.lang.String[] { "Name", "Age", "Like", "Son", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
