logging:
  config: classpath:log4j2.yml
dubbo:
  application:
    name: netty-client
  protocol:
    name: dubbo
    port: 20802
  consumer:
    check: false
    timeout: 5000
    retries: 0
  registry:
    address: zookeeper://127.0.0.1:2181